"""Keep the manual's navigation in sync with its files.

- Regenerates the `nav:` block in mkdocs.yml from the folder structure
- Rewrites each chapter's closing "**Next:**" line to point at the next chapter

Run it after adding or renaming chapters:  python scripts/sync_manual.py
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANUAL = ROOT / "manual"
PARTS = {
    "part-1-foundations": "I · Foundations",
    "part-2-mcp-and-connectors": "II · MCP & Connectors",
    "part-3-automation": "III · Automation",
    "part-4-ai-in-your-apps": "IV · AI in Your Apps",
    "part-5-building-with-ai": "V · Building with AI",
    "part-6-knowledge-and-memory": "VI · Knowledge & Memory",
    "part-7-local-ai": "VII · Local AI",
    "part-8-creative-ai": "VIII · Creative AI",
    "part-9-ai-for-life-and-work": "IX · AI for Life & Work",
    "part-10-mastery": "X · Mastery",
    "appendices": "Appendices",
}


def title_of(path: Path) -> str:
    """The chapter's H1, trimmed to a short nav-friendly title ("04 · MCP Explained")."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            title = line[2:].split(":")[0]
            return re.sub(r"[^\w)&'!?.]+$", "", title.strip())
    return path.stem


def chapters() -> list[tuple[str, list[Path]]]:
    out = []
    for folder, label in PARTS.items():
        files = sorted((MANUAL / folder).glob("*.md")) if (MANUAL / folder).is_dir() else []
        if files:
            out.append((label, files))
    return out


def yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def sync_nav(parts) -> None:
    lines = ["nav:", f"  - {yaml_str('🏠 Home')}: index.md"]
    for label, files in parts:
        lines.append(f"  - {yaml_str(label)}:")
        for f in files:
            lines.append(f"      - {yaml_str(title_of(f))}: {f.relative_to(MANUAL).as_posix()}")
    cfg = ROOT / "mkdocs.yml"
    text = cfg.read_text(encoding="utf-8")
    block = "# NAV:START (generated by scripts/sync_manual.py; do not edit by hand)\n" + "\n".join(lines) + "\n# NAV:END"
    text = re.sub(r"# NAV:START.*?# NAV:END", lambda _: block, text, flags=re.S)
    cfg.write_text(text, encoding="utf-8")


def sync_next_links(parts) -> None:
    ordered = [f for _, files in parts for f in files]
    for i, f in enumerate(ordered):
        if i + 1 < len(ordered):
            nxt = ordered[i + 1]
            rel = os.path.relpath(nxt, f.parent).replace(os.sep, "/")
            line = f"**Next:** [{title_of(nxt)} →]({rel})"
        else:
            home = os.path.relpath(MANUAL / "index.md", f.parent).replace(os.sep, "/")
            line = f"**You made it to the end! 🎉** [Back to the manual home ↩]({home})"
        text = f.read_text(encoding="utf-8").rstrip("\n").split("\n")
        if text and (text[-1].startswith("**Next:**") or text[-1].startswith("**You made it")):
            text[-1] = line
        else:
            text += ["", "---", "", line]
        f.write_text("\n".join(text) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parts = chapters()
    sync_nav(parts)
    sync_next_links(parts)
    print(f"Synced {sum(len(f) for _, f in parts)} pages across {len(parts)} sections.")
